version: "3"

services:
  app:
    image: flask_app_template:latest
    build: 
      context: ./config
      dockerfile: app.Dockerfile
    env_file: ./config/.env
    container_name: app
    expose:
      - "5000"
    networks:
      - server_net
    volumes:
      - ./app:/var/app
    working_dir: /var/app
    command: ["gunicorn", "-c/var/tmp/conf.py", "app:create_app()"]
  server:
    image: flask_app_server:latest
    build: 
      context: ./config
      dockerfile: nginx.Dockerfile
    container_name: server
    #command: [nginx-debug, '-g', 'daemon off;']
    #restart: on-failure
    networks:
      - server_net
    volumes:
      - ./app/static:/srv/static
    ports:
      - "80:80"
    depends_on:
      - app

networks:
  server_net:

