version: '3'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env.dev
    networks:
      - app_network
  clint:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    
    command: ["npm", "start"]
    volumes:
      #- '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network
  # client:
  #   container_name: client
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile     
  #   volumes:
  #     - './:/app'
  #     - '/app/node_modules'
  #   command: ["npm", "start"]
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

networks:
  app_network:

volumes:
  postgres_data:
  node-modules:
         
